[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Éditer"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS-LIGNE"
mojangStatus = "STATUS MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "NOUVELLES"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "ATTENDEZ SVP.."
newsNavigationStatus = "{currentPage} of {totalPages}"
newsErrorLoadSpan = "RECHERCHE DE NOUVELLES"
newsErrorFailedSpan = "IMPOSSIBLE DE CHERGER LES NOUVELLES"
newsErrorRetryButton = "RÉÉSSAYER"
newsErrorNoneSpan = "AUCUNE NOUVELLES"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION À MINECRAFT"
loginEmailError = "* VALEUR INVALIDE"
loginEmailPlaceholder = "E-MAIL OU PSEUDO"
loginPasswordError = "* REQUIS"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "Mot de passe oublié?"
loginRememberMeText = "Se rappeler de moi"
loginButtonText = "Se connecter"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n'est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Connexion via Microsoft"
loginWithMojang = "Connexion via Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un Compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Fait"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajoutez de nouveaux comptes ou gérez ceux existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Se connecter automatiquement au serveur au lancement."
launchDetachedTitle = "Lancer le processus de jeu détaché du lanceur."
launchDetachedDesc = "Si le jeu n'est pas détaché, la fermeture du lanceur fermera également le jeu."
tabModsHeaderText = "Paramètres des Mods"
tabModsHeaderDesc = "Activer/désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods Requis"
optionalMods = "Mods Optionnels"
dropinMods = "Mods instantanés"
addMods = "Ajouter des Mods"
dropinRefreshNote = "(F5 pour rafraîchir)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Activer ou désactiver les shaders. Veuillez noter que les shaders ne fonctionneront correctement que sur des configurations puissantes. Vous pouvez ajouter des packs personnalisés ici."
selectShaderpack = "Ajouter des Shaderpack"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire (RAM)"
maxRAM = "RAM Maximum"
minRAM = "RAM Minimum"
memoryDesc = "La RAM minimale recommandée est de 3 Go. Définir les valeurs minimale et maximale sur la même valeur peut réduire le lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l'exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'exécutable Java est validé avant le lancement du jeu."
javaPathDesc = "Le chemin devrait se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options à fournir à la JVM au moment de l'exécution. <em>-Xms</em> and <em>-Xmx</em> ne devrait pas être inclus."
launcherTabHeaderText = "Paramètres du Launcher"
launcherTabHeaderDesc = "Options liées au lanceur lui-même."
allowPrereleaseTitle = "Autoriser les mises à jour BETA."
allowPrereleaseDesc = "Les versions BETA incluent de nouvelles fonctionnalités qui n'ont peut-être pas été entièrement testées ou intégrées.<br>Cela sera toujours vrai si vous utilisez une version BETA."
dataDirectoryTitle = "Répertoire de données"
selectDataDirectory = "Sélectionner le répertoire de données"
chooseFolder = "Choisir le dossier"
dataDirectoryDesc = "Tous les fichiers de jeu et les installations Java locales seront stockés dans le répertoire de données.<br>Les captures d'écran et les sauvegardes mondiales sont stockées dans le dossier d'instance pour la configuration de serveur correspondante."
aboutTabHeaderText = "À Propos"
aboutTabHeaderDesc = "Afficher les informations et les notes de version pour la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "DevTools Console"
releaseNotes = "Notes de version"
changelog = "Journal des modifications"
noReleaseNotes = "Aucune note de version"
viewReleaseNotes = "Afficher les notes de version sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du lanceur"
launcherUpdatesHeaderDesc = "Téléchargez, installez et consultez les mises à jour du lanceur."
checkForUpdates = "Recherche de mises à jour "
whatsNew = "Quoi de neuf"
updateReleaseNotes = "Mettre à jour les notes de version"

[ejs.waiting]
waitingText = "En attendant Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En attente du client.."
state = "Serveur: {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "Connexion"
loggingIn = "SE CONNECTER"
success = "SUCCÈS"
tryAgain = "RÉÉSSAYER

[js.login.error]
invalidValue = "# Valeur Invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Attendez SVP.."
failureTitle = "Erreur lors du lancement"
failureText = "Voir console (CTRL + Shift + i) pour plus de détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS-LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des informations système.."
noCompatibleJava = "Installation<br>java incompatible"
installJavaMessage = "Pour lancer Minecraft, vous avez besoin d'une installation 64 bits de Java {major}. Souhaitez-vous que nous en installions une copie ?"
installJava = "Installation de Java"
installJavaManually = "Installation Manuelle"
javaDownloadPrepare = "Préparation du téléchargement Java.."
javaDownloadFailureTitle = "Erreur lors du téléchargement Java"
javaDownloadFailureText = "Voir console (CTRL + Shift + i) pour plus de détails."
javaRequired = "Java est requis<br>to Launch"
javaRequiredMessage = 'Une installation valide de Java x64 {major} est requise pour démarrer.<br><br>Veuillez vous référer à notre <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Guide de gestion de Java</a> pour des instructions sur comment installer manuellement Java.'
javaRequiredDismiss = "Je comprends"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver la distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé a un mauvais hachage, le fichier est peut-être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations sur le serveur.."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger une copie de l'index de distribution. Voir la console (CTRL + Shift + i) pour plus de détails."
pleaseWait = "Attendez SVP"
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Voir console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Validation de l'intégrité des fichiers.."
errorDuringFileVerificationTitle = "Erreur lors de la vérification du fichier"
downloadingFiles = "Téléchargement de fichiers.."
errorDuringFileDownloadTitle = "Erreur lors du téléchargement du fichier"
preparingToLaunch = "Préparation du lancement.."
launchingGame = "Lancement du jeu.."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n'a pas pu être téléchargé correctement. Par conséquent, le jeu ne peut pas se lancer.<br><br>Pour résoudre ce problème, désactivez temporairement votre logiciel antivirus et relancez le jeu.<br><br>Si vous avez le temps, veuillez <a href=\" https://github.com/dscalzi/HeliosLauncher/issues\">soumettez un problème</a> et dites-nous quel logiciel antivirus vous utilisez. Nous allons les contacter et essayer de mettre les choses au clair."
doneEnjoyServer = "Fait. Profitez du serveur !"
checkConsoleForDetails = "Veuillez consulter la console (CTRL + Shift + i) pour plus de détails."

[js.landing.news]
checking = "Recherche de nouvelles"

[js.landing.discord]
loading = "Chargement du jeu.."
joining = "Navigation vers SlyWorld !"
joined = "Explorer le royaume !"

[js.overlay]
dismiss = "Rejeter"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Quelque chose s'est mal passé"
errorMessage = "L'authentification Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Quelque chose s'est mal passé"
errorMessage = "La déconnexion de Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionnez un compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Ceci est votre dernier compte"
lastAccountWarningMessage = "Pour utiliser le lanceur, vous devez être connecté à au moins un compte. Vous devrez ensuite vous reconnecter.<br><br>Êtes-vous sûr de vouloir vous déconnecter ?"
confirmButton = "Je suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Pseudo"
uuid = "UUID"
selectAccount = "Sélectionner un compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Se déconnecter"

[js.settings.dropinMods]
removeButton = "Retirer"
deleteFailedTitle = "Échec de la suppression<br>Mod Drop-in {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas utilisé et réessayez."
failedToggleTitle = "Échec de l'activation/désactivation d'un ou plusieurs modules instantanés"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Main Server"

[js.settings.java]
selectedJava = "Sélectionné: Java {version} ({vendor})"
invalidSelection = "Sélection Invalide"
requiresJava = "Requiert Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-version"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Impossible de charger les notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle pré-version disponible"
downloadingButton = "Téléchargement.."
downloadButton = 'Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le lanceur et exécutez le dmg pour mettre à jour.</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification des mises à jour.."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Nous n'avons pas pu authentifier votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : impossible de charger l'index de distribution"
fatalErrorMessage = "Une connexion n'a pas pu être établie avec nos serveurs pour télécharger l'index de distribution. Aucune copie locale n'était disponible pour le chargement. <br><br>L'index de distribution est un fichier essentiel qui fournit les dernières informations sur le serveur. Le lanceur ne peut pas démarrer sans cela. Assurez-vous d'être connecté à Internet et relancez l'application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de l'actualisation de la connexion"
failedMessage = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez sélectionner un autre compte ou vous connecter à nouveau."
failedMessageSelectAnotherAccount = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Se Connecter"
selectAnotherAccountButton = "Sélectionner un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer Maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur lors de la connexion:<br>Profil non configuré"
noProfileDesc = "Votre compte Microsoft n'a pas encore de profil Minecraft configuré. Si vous avez récemment acheté le jeu ou l'avez utilisé via Xbox Game Pass, vous devez configurer votre profil sur <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous n'avez pas encore acheté le jeu, vous pouvez également le faire sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur lors de la connexion:<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n'est associé à aucun compte Xbox."
xblBannedTitle = "Erreur lors de la connexion:<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte Microsoft provient d'un pays où Xbox Live n'est pas disponible ou interdit."
under18Title = "Erreur lors de la connexion :<br>Approbation parentale requise"
under18Desc = "Les comptes des utilisateurs de moins de 18 ans doivent être ajoutés à une famille par un adulte."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne:<br>Méthode Non Autorisée"
methodNotAllowedDesc = "Méthode Non Autorisée. Veuillez signaler cette erreur."
notFoundTitle = "Erreur interne:<br>Pas trouvé"
notFoundDesc = "Le point de terminaison d'authentification est introuvable. Veuillez signaler ce problème."
accountMigratedTitle = "Erreur lors de la connexion:<br>Compte migré"
accountMigratedDesc = "Vous avez tenté de vous connecter avec un compte migré. Réessayez en utilisant l'adresse e-mail du compte comme nom d'utilisateur."
invalidCredentialsTitle = "Erreur lors de la connexion:<br>Les informations d'identification sont invalides"
invalidCredentialsDesc = "L'e-mail ou le mot de passe que vous avez saisi est incorrect. Veuillez réessayer."
tooManyAttemptsTitle = "Erreur lors de la connexion : trop de tentatives"
tooManyAttemptsDesc = "Il y a eu trop de tentatives de connexion avec ce compte récemment. Veuillez réessayer plus tard."
invalidTokenTitle = "Erreur lors de la connexion :<br>Jeton invalide"
invalidTokenDesc = "Le jeton d'accès fourni n'est pas valide."
tokenHasProfileTitle = "Erreur lors de la connexion:<br>Le jeton a un profil"
tokenHasProfileDesc = "Le jeton d’accès a déjà un profil attribué. La sélection des profils n'est pas encore implémentée."
credentialsMissingTitle = "Erreur lors de la connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Le nom d'utilisateur/mot de passe n'a pas été soumis ou le mot de passe contient moins de 3 caractères."
invalidSaltVersionTitle = "Erreur lors de la connexion :<br>Version Salt invalide"
invalidSaltVersionDesc = "Version Salt invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type de média non pris en charge"
unsupportedMediaTypeDesc = "Type de média non pris en charge. Veuillez signaler cette erreur."
accountGoneTitle = "Erreur lors de la connexion :<br>Compte migré"
accountGoneDesc = "Le compte a été migré vers un compte Microsoft. Veuillez vous connecter avec Microsoft."
unreachableTitle = "Erreur lors de la connexion :<br>Injoignable"
unreachableDesc = "Impossible d'atteindre les serveurs d'authentification. Assurez-vous qu'ils sont en ligne et que vous êtes connecté à Internet."
gameNotPurchasedTitle = "Erreur lors de la connexion :<br>Jeu non acheté"
gameNotPurchasedDesc = "Le compte avec lequel vous essayez de vous connecter n’a pas acheté de copie de Minecraft. Vous pouvez en acheter un exemplaire sur <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erreur inconnue lors de la connexion"
unknownErrorDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."
